-- 1. Number of Sales Opportunities by Month
SELECT MONTH(ENGAGE_DATE) AS Month,
COUNT(*) AS Sales_Opportunity
FROM SALES_PIPELINE
WHERE MONTH(ENGAGE_DATE) IS NOT NULL
GROUP BY MONTH(ENGAGE_DATE)
ORDER BY COUNT(*) DESC;

-- 2. Win Rate for Each Product
SELECT PRODUCT,
(SUM(CASE WHEN DEAL_STAGE = 'Won' THEN 1 ELSE 0 END) / COUNT(DEAL_STAGE)) AS Win_Rate
FROM SALES_PIPELINE
GROUP BY PRODUCT
ORDER BY (SUM(CASE WHEN DEAL_STAGE = 'Won' THEN 1 ELSE 0 END) / COUNT(DEAL_STAGE)) DESC;

-- 3. Win Rate for Each Agent
SELECT SALES_AGENT AS Agent,
(SUM(CASE WHEN DEAL_STAGE = 'Won' THEN 1 ELSE 0 END) / COUNT(DEAL_STAGE)) AS Win_Rate
FROM SALES_PIPELINE
GROUP BY SALES_AGENT
ORDER BY (SUM(CASE WHEN DEAL_STAGE = 'Won' THEN 1 ELSE 0 END) / COUNT(DEAL_STAGE)) DESC;

-- 4. Total Revenue by Agent
SELECT SALES_AGENT AS Agent,
SUM(CLOSE_VALUE) AS Total_Revenue
FROM SALES_PIPELINE
GROUP BY SALES_AGENT
ORDER BY SUM(CLOSE_VALUE) DESC;

-- 5. Total Revenue by Product
SELECT PRODUCT,
SUM(CLOSE_VALUE) AS Total_Revenue
FROM SALES_PIPELINE
GROUP BY PRODUCT
ORDER BY SUM(CLOSE_VALUE) DESC;

-- 6. Total Revenue by Industry
SELECT SECTOR AS Industry,
SUM(REVENUE) AS Total_Revenue
FROM ACCOUNTS
GROUP BY SECTOR
ORDER BY SUM(REVENUE) DESC;
